Fix TWCC not being reset when adding the first pad
membraneframework/membrane_rtp_plugin pull request #136
Opened 2023-02-01 10:57 UTC by daniel-jodlos

2023-02-01 14:38 UTC, bblaszkow06 approved these changes

2023-02-01 14:38 UTC, bblaszkow06 commented on lib/membrane/rtp/twcc_sender.ex
> +      |> then(&(&1 != 0))
```suggestion
      |> Map.values()
      |> Enum.any?(&(&1.ref != pad and &1.direction == :input))
```

or using only one iteration

```suggestion
      |> Enum.any?(fn
        {ref, %{direction: :input}} when ref != pad -> true
        _else -> false
      end)
```

2023-02-01 15:28 UTC, bblaszkow06 requested changes

2023-02-01 15:28 UTC, bblaszkow06 commented on lib/membrane/rtp/twcc_sender.ex
> +  def handle_pad_added(pad, ctx, state) do
Oh, w8, one more thing - we should only invoke this when new input pad is added, otherwise we will reset `cc` twice

2023-02-01 22:01 UTC, mickel8 reviewed
To me it looks suspicious. 

I would expect that if we don't send any packets we also won't get any TWCC reports. If we don't get any TWCC reports, the estimation should stay unchanged. 

That's how we update cc

```elixir
    cc =
      CongestionControl.update(
        state.cc,
        reference_time,
        receive_deltas,
        send_deltas,
        packet_sizes,
        rtt
      )
```

where reference time is taken from the last received TWCC report. So we have differences between sent packets, received packets and current rtt. Doesn't look like the time when we created CC struct should have any impact on the estimation :thinking: 

Maybe there is something inside CC struct that makes it time sensitive

2023-02-02 05:11 UTC, daniel-jodlos commented
> If we don't get any TWCC reports, the estimation should stay unchanged.

And it does. Until we receive a packet, then it drops to basically nothing.

> Doesn't look like the time when we created CC struct should have any impact on the estimation thinking

It does. `r_hat` calculation uses time window to estimate the receiver rate and it doesn't have its own clock - it relies on RTP and RTCP packets to update.  It makes perfect sense to me, that when you have a 750ms window, and you don't send any packets for a while, and then you send one, rr it estimated to be 4/3 of the size of your packet and the estimation is adjusted accordingly.

2023-02-02 09:21 UTC, bblaszkow06 approved these changes

2023-02-06 04:51 UTC, merged