Replace buffer store with a map
membraneframework/membrane_rtp_plugin pull request #143
Opened 2023-02-08 08:58 UTC by mickel8

2023-02-08 15:49 UTC, bblaszkow06 requested changes

2023-02-08 15:49 UTC, bblaszkow06 commented on lib/membrane/rtp/outbound_rtx_controller.ex
> +    buffers_to_retransmit = Enum.reject(buffers, fn buffer -> buffer == nil end)
```suggestion
    buffers_to_retransmit = Enum.reject(buffers, &is_nil/1)
```

2023-02-08 15:49 UTC, bblaszkow06 commented on lib/membrane/rtp/outbound_rtx_controller.ex
> +      store = Map.put(store, seq_num, {now, buffer})
IIUC, you should be putting the tuple under idx, not `seq_num`.
```suggestion
      store = Map.put(store, idx, {now, buffer})
```

2023-02-08 15:49 UTC, bblaszkow06 commented on lib/membrane/rtp/outbound_rtx_controller.ex
>          )
I'd compact this log a bit: (cannot make suggestions due to deleted lines, GH sux)

```elixir
    unless buffers_to_retransmit == [] do
      Membrane.Logger.info("""
      Retransmitting (#{length(buffers_to_retransmit)}) buffers, sequence numbers:
      #{inspect(Enum.map(buffers_to_retransmit, & &1.metadata.rtp.sequence_number))}
      """)
    end
```

2023-02-08 16:23 UTC, bblaszkow06 commented on lib/membrane/rtp/outbound_rtx_controller.ex
> +    state = put_in(state, [:store, idx], {System.monotonic_time(:millisecond), buffer})
One more thing: this changes the behaviour of the controller as we won't retransmit any packet within 10ms. I assume the receiver is using some JitterBuffer and will wait a bit before sending NACK to compensate for possible reorder, thus we should handle first NACK right away.

I even wonder if we should have any `min_rtx_interval` at all, as it seems large retransmissions are only a symptom, not a root cause of our problems

2023-02-13 15:58 UTC, mickel8 commented
New figures 

In ~240 seconds we perform ~27-30M of reductions which is about 8-11M less than using BufferStore

`total_buffers_sent` is multiplied by 1000, awaiting buffers and message_queue_len are multiplied by 10 000 000

![visualization (8)](https://user-images.githubusercontent.com/24651552/218507521-4855dff3-2487-4b25-9e15-d20295d51612.svg)

![visualization (7)](https://user-images.githubusercontent.com/24651552/218507423-bb0545c9-667f-480d-9501-756f87e9bfa8.svg)

![visualization (5)](https://user-images.githubusercontent.com/24651552/218505718-0a32d113-999b-4949-a223-b0d003970c98.svg)

2023-02-13 16:13 UTC, bblaszkow06 approved these changes

2023-02-13 16:13 UTC, bblaszkow06 commented on lib/membrane/rtp/outbound_rtx_controller.ex
> +  def handle_init(_opts), do: {:ok, %{store: %{}, last_rtx_times: %{}}}
```suggestion
  def handle_init(_opts), do: {:ok, %{store: %{}}}
```

2023-02-13 16:21 UTC, merged