Forward rtcp sender packet event
membraneframework/membrane_rtp_plugin pull request #168
Opened 2024-05-17 14:21 UTC by Karolk99

2024-05-20 08:04 UTC, mat-hek approved these changes

2024-05-20 14:21 UTC, mickel8 requested changes
Can we update RTCP section in SessionBin docs?

2024-05-21 15:28 UTC, Karolk99 commented on lib/membrane/rtp/session_bin.ex
> +  RTCP sender reports are dispatched as `Membrane.RTCP.SenderReportPacket` events on session bin `:output` pads
only inboud RTCP sender packets

2024-05-21 16:31 UTC, mickel8 requested changes

2024-05-21 16:31 UTC, mickel8 commented on lib/membrane/rtp/session_bin.ex
>    RTCP for outbound stream is not yet supported. # But will be :)
This is outdated too :eyes:

2024-05-22 08:58 UTC, Karolk99 commented on lib/membrane/rtp/session_bin.ex
>    RTCP for outbound stream is not yet supported. # But will be :)
I will check it once again.

2024-05-23 09:52 UTC, mickel8 approved these changes

2024-05-23 09:52 UTC, mickel8 commented on lib/membrane/rtp/session_bin.ex
> +  RTCP packets will only be produced if rtcp_receiver_report_interval option is set to a value other than nil.
```suggestion
  RTCP packets for the outbound stream are available on `rtcp_sender_output` pad.
  RTCP packets will only be produced if rtcp_sender_report_interval option is set to a value other than nil.
```

2024-05-23 10:00 UTC, mat-hek approved these changes

2024-05-23 15:59 UTC, merged